import { proto } from "@whiskeysockets/baileys";

export const IMessageArray: (keyof proto.IMessage)[] = [
	"conversation",
	"senderKeyDistributionMessage",
	"imageMessage",
	"contactMessage",
	"locationMessage",
	"extendedTextMessage",
	"documentMessage",
	"audioMessage",
	"videoMessage",
	"call",
	"chat",
	"protocolMessage",
	"contactsArrayMessage",
	"highlyStructuredMessage",
	"fastRatchetKeySenderKeyDistributionMessage",
	"sendPaymentMessage",
	"liveLocationMessage",
	"requestPaymentMessage",
	"declinePaymentRequestMessage",
	"cancelPaymentRequestMessage",
	"templateMessage",
	"stickerMessage",
	"groupInviteMessage",
	"templateButtonReplyMessage",
	"productMessage",
	"deviceSentMessage",
	"messageContextInfo",
	"listMessage",
	"viewOnceMessage",
	"orderMessage",
	"listResponseMessage",
	"ephemeralMessage",
	"invoiceMessage",
	"buttonsMessage",
	"buttonsResponseMessage",
	"paymentInviteMessage",
	"interactiveMessage",
	"reactionMessage",
	"stickerSyncRmrMessage",
	"interactiveResponseMessage",
	"pollCreationMessage",
	"pollUpdateMessage",
	"keepInChatMessage",
	"documentWithCaptionMessage",
	"requestPhoneNumberMessage",
	"viewOnceMessageV2",
	"encReactionMessage",
	"editedMessage",
	"viewOnceMessageV2Extension",
	"pollCreationMessageV2",
	"scheduledCallCreationMessage",
	"groupMentionedMessage",
	"pinInChatMessage",
	"pollCreationMessageV3",
	"scheduledCallEditMessage",
	"ptvMessage",
	"botInvokeMessage",
	"callLogMesssage",
	"messageHistoryBundle",
	"encCommentMessage",
	"bcallMessage",
	"lottieStickerMessage",
	"eventMessage",
	"commentMessage",
	"newsletterAdminInviteMessage",
	"extendedTextMessageWithParentKey",
	"placeholderMessage",
	"encEventUpdateMessage",
];

export const MessageArray: (keyof typeof proto.Message)[] = [
	"ExtendedTextMessage",
	"FutureProofMessage",
	"AudioMessage",
	"ImageMessage",
	"VideoMessage",
	"StickerMessage",
	"DocumentMessage",
];

export const MessageTypes: {
	[key: string]: keyof proto.Message;
} = {
	videoMessage: "VideoMessage" as keyof proto.Message,
	imageMessage: "ImageMessage" as keyof proto.Message,
	audioMessage: "AudioMessage" as keyof proto.Message,
	documentMessage: "DocumentMessage" as keyof proto.Message,
};
