#!/usr/bin/env bash

set -e -o pipefail

cd "$(dirname "$0")/.." || exit 1

rm -rf dist
mkdir dist

### SETUP ###
# make copy of the original file
cp node_modules/baileys/lib/Socket/index.d.ts dist/lib.Socket.baileys.d.ts
# replace the import
sed -i 's/import("long").Long/import("long")/g' node_modules/baileys/lib/Socket/index.d.ts

# compile.
npm exec tsc

### POST-COMPILE ###
# restore the original file
mv dist/lib.Socket.baileys.d.ts node_modules/baileys/lib/Socket/index.d.ts

# Create a module type definition file
cp dist/index.d.ts dist/index.d.mts

# Make sure isomorphic module works
(cd dist && node -e 'require("@frierendv/frieren")')
(cd dist && node -e 'import("@frierendv/frieren")' --input-type=module)
