#!/usr/bin/env bash

set -e -o pipefail

cd "$(dirname "$0")/.."

rm -rf dist
mkdir dist

# make copy of the original file
cp node_modules/baileys/lib/Socket/index.d.ts dist/baileys.d.ts
# replace the import
sed -i 's/import("long").Long/import("long")/g' node_modules/baileys/lib/Socket/index.d.ts

# compile.
npm exec tsc-multi

# restore the original file
mv dist/baileys.d.ts node_modules/baileys/lib/Socket/index.d.ts

cp dist/index.d.ts dist/index.d.mts

# Make sure isomorphic module works
(cd dist && node -e 'require("frieren")')
(cd dist && node -e 'import("frieren")' --input-type=module)
